In [18]:
import torch
import torch.nn as nn

In [6]:
device = "cuda" if torch.cuda.is_available() else "cpu"
torch.set_default_device(device)

In [9]:
print(device)
print(torch.ones((2, 3)))

cuda
tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')


In [11]:
tensora = torch.tensor([1, 2, 3])
tensorb = torch.tensor([4, 5, 6])
tensorc = torch.tensor([7, 8, 9])
print(torch.stack((tensora, tensorb, tensorc)))

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], device='cuda:0')


In [28]:
tensor = torch.randn((2, 4))
print(tensor)
print(torch.softmax(tensor, dim=0))
print(torch.softmax(tensor, dim=1))

tensor([[-0.9593, -0.4157,  0.9850, -0.1516],
        [-2.3875,  0.9092,  0.1652,  1.9316]], device='cuda:0')
tensor([[0.8066, 0.2100, 0.6942, 0.1107],
        [0.1934, 0.7900, 0.3058, 0.8893]], device='cuda:0')
tensor([[0.0837, 0.1441, 0.5846, 0.1876],
        [0.0086, 0.2330, 0.1107, 0.6477]], device='cuda:0')


Embeddings