MLP --> Multilayer Perceptron

In [3]:
import torch
from torch import nn
import torch.nn.functional as F

device = "cuda" if torch.cuda.is_available() else "cpu"
torch.set_default_device(device)
print(device)

cuda


Generate data (or rather organize it)

In [ ]:
with open("names.txt", 'r', encoding="UTF-8") as f:
    text = f.read()
    words = text.splitlines()
    chars = sorted(set("".join(words)))

stoi = {char:integer+1 for integer,char in enumerate(chars)}
itos = {integer+1:char for integer,char in enumerate(chars)}

stoi["."] = 0
itos[0] = "."


In [ ]:
test_list = [1, 2, 3]
print(test_list[1:] + [5])
#test_list[1:] basically gets all elements besides the first
#+ [5] and an element 5 to the list
#with that you can add an element to the list while removing the first one and moving all the rest to the left

[2, 3, 5]


In [ ]:
block_size = 3 #How many characters of context is passed through the neural network
inputs, labels = [], []
for w in words[:1]:
    context = [0] * block_size
    for ch in w + '.':
        ix = stoi[ch]
        inputs.append(context)
        labels.append(ix)
        context = context[1:] + [ix]
        #print(context[1:]+[ix])

inputs = torch.tensor(inputs)
labels = torch.tensor(labels)

print(inputs)
print(labels)

NameError: name 'words' is not defined

In [ ]:
one_hot_test = F.one_hot(torch.tensor(5), num_classes=27).type(torch.float)
print(one_hot_test)
C = torch.randn((27,2))
print(one_hot_test @ C)
#The same as print(C[5])
print(C[5])

tensor([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.], device='cuda:0')
tensor([-0.1538, -1.4984], device='cuda:0')
tensor([-0.1538, -1.4984], device='cuda:0')


In [ ]:
print(C)

tensor([[ 0.7981, -0.0783],
        [ 0.3485, -1.2172],
        [ 0.7550, -1.0599],
        [ 0.0894,  1.7146],
        [-0.0593,  0.6477],
        [-0.1538, -1.4984],
        [-0.4471, -1.7794],
        [-0.9464,  0.3930],
        [ 1.1104, -0.3061],
        [ 0.3065, -0.2680],
        [-0.1490, -0.8429],
        [-0.3086,  0.0465],
        [ 0.0498,  0.2474],
        [-0.0670,  0.0459],
        [-0.6095, -1.0004],
        [ 1.4939,  1.1517],
        [ 1.1654, -0.5093],
        [ 1.9525, -0.2488],
        [ 1.0903,  0.2725],
        [-1.4784, -1.2951],
        [-1.4499, -0.0773],
        [ 1.2361, -1.4450],
        [ 0.8990, -0.4989],
        [ 0.3128, -0.4102],
        [-1.5923, -1.1982],
        [-0.5754, -2.1554],
        [ 2.8619,  0.9979]], device='cuda:0')


In [ ]:
print(C[[0, 1, 2, 2, 2, 2]])

tensor([[ 0.7981, -0.0783],
        [ 0.3485, -1.2172],
        [ 0.7550, -1.0599],
        [ 0.7550, -1.0599],
        [ 0.7550, -1.0599],
        [ 0.7550, -1.0599]], device='cuda:0')


In [ ]:
print(inputs.shape)
embedding_tensor = C[inputs]
print(embedding_tensor.shape)

torch.Size([32, 3])
torch.Size([32, 3, 2])


In [ ]:
print(inputs[13, 2])
print(f"It's embedding is --> {C[inputs][13, 2]}")
print(embedding_tensor.shape)

tensor(1, device='cuda:0')
It's embedding is --> tensor([ 0.3485, -1.2172], device='cuda:0')
torch.Size([32, 3, 2])


In [ ]:
W1 = torch.randn((3*2, 100))
b1 = torch.randn(100)

#torch.cat(torch.unbind(embedding_tensor, 1), 1)
#embedding_tensor.view(32, 6)

hidden_layer = embedding_tensor.view(embedding_tensor.shape[0], 6) @ W1 + b1
print(hidden_layer)

tensor([[-1.2243,  0.6019,  1.9300,  ..., -2.3778, -2.5337, -0.0449],
        [-1.0235, -1.4281,  2.4067,  ..., -3.0274, -0.5796, -0.0302],
        [-2.6114,  0.9983,  1.3733,  ..., -4.8258, -1.7975, -0.2736],
        ...,
        [-0.3432,  4.6050,  0.6647,  ..., -3.5701, -3.1829,  0.0409],
        [-1.9055,  0.3213,  2.5429,  ..., -4.2802, -2.5021, -0.4322],
        [-0.8311, -1.5839,  2.3990,  ..., -3.1695, -2.0122,  0.0398]],
       device='cuda:0')
